### ISSUE TITLE
Customising and `source`

### ISSUE THREAD

**Issue by matteocorti** [caarlos0/shell-ci-build#16]
I tried to customise the check by only checking one single script

```
#!/usr/bin/env bash
set -eo pipe fail
source ./shell-ci-build/build.sh
check "./check_ssl_cert"
```

where `shell-ci-build` is the directory where the module is checked out and `check_ssl_cert` is the script to be checked.

When I execute the script by `source` the function `is executed (which seems correct as it is the last command of the`build.sh` script).

**Comment by matteocorti** [comment]
Actually the documentation should only be updated by removing the `source` line which is not necessary, as it is possible to invoke `spellcheck` directly.

If the coloured output is a must:

```
#!/usr/bin/env bash
set -eo pipefail

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] Linting %s...\n" "$1"
}

fail() {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] Linting %s...\n" "$1"
  exit 1
}

check() {
  local script="$1"
  shellcheck "$script" || fail "$script"
  success "$script"
}

check "$1"
```

**Comment by caarlos0** [comment]
@matteocorti Thanks for the bug report. Will try to fix this later.

**Comment by caarlos0** [comment]
@matteocorti please check #17.

Don't forget to [update your submodules](https://github.com/caarlos0/shell-ci-build#updating).

**Comment by caarlos0** [comment]
@matteocorti BTW, there is a typo in your example: in `set -eo pipe fail` it should be `set -eo pipefail`.
