### ISSUE TITLE
Check all scripts first, then exit with non-zero code if any problem was found

### ISSUE THREAD

**Issue by Nowaker** [caarlos0/shell-ci-build#26]
It make more sense to present all errors and then exit. This way a developer can see all problems and fix them in one go, instead of playing ping pong with the CI system.

**Comment by caarlos0** [comment]
I wasn't able to do that with plain old shell. I also wanted to add more checkers.

Can you try https://github.com/caarlos0/shcheck please?

**Comment by Nowaker** [comment]
Howdy! I don't work on a project I used shell-ci-build in any more so I won't check it out but I noted your heads-up and starred the repo. Will check next time! Many thanks. :+1:

**Comment by caarlos0** [comment]
since this can't be made without too many hacks, closing.
